### ISSUE TITLE
Component not working with vuetify new v2.0.19

### ISSUE THREAD

**Issue by raphael-jolimoi** [darrenfang/vuetify-datetime-picker#42]
It seems there were breaking changes for the timer

**Comment by darrenfang** [comment]
Yes. This cause by the `Time Picker` component. 

Reset the style `.v-picker__body`:

```css
.v-picker__body {
    margin: initial;
}
```
