### ISSUE TITLE
Cannot target dialog classes because dialog has no classname.

### ISSUE THREAD

**Issue by Flamenco** [darrenfang/vuetify-datetime-picker#90]
By adding a classname to the dialog, I will be able to target dialog classes.

```css
.dialog-datetime-picker {
  .v-tabs-slider {
    background-color: red;
  }
}
```

Before:
<img width="344" alt="Screen Shot 2020-12-09 at 11 17 43 AM" src="https://user-images.githubusercontent.com/819940/101655954-2df74680-3a10-11eb-8e20-cff13e69ee77.png">

After:
<img width="356" alt="Screen Shot 2020-12-09 at 11 14 54 AM" src="https://user-images.githubusercontent.com/819940/101655890-1ddf6700-3a10-11eb-8b2d-23b983560db7.png">
